<a href="https://colab.research.google.com/github/wantfree8937/Machine/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EA%B3%BC%EC%A0%9C3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# (실습) 넘파이 어레이

**주의사항**

- `None`은 적절한 표현식으로 대체한다.
- `Pass`는 적절한 명령문으로 대체한다.

## numpy 모듈

**문제 1**

아래 코드를 설명하라.

In [1]:
import numpy as np

`코드설명`: numpy 라이브러리를 가져와 np라는 이름을 부여한다.

아래 코드는 수정하지 마세요!!!

In [2]:
np.__version__

'1.22.4'

**문제 2**

아래 코드의 기능을 설명하라

In [3]:
np.random.seed(42)

`코드설명`: 랜덤 시드, 난수 생성

**문제 3**

부동소수점으로 구성된 어레이의 항목은 기본적으로 소수점 이하 8자리까지 출력한다.

In [4]:
Z = np.random.random((40,40))
Z

array([[0.37454012, 0.95071431, 0.73199394, ..., 0.09767211, 0.68423303,
        0.44015249],
       [0.12203823, 0.49517691, 0.03438852, ..., 0.07404465, 0.35846573,
        0.11586906],
       [0.86310343, 0.62329813, 0.33089802, ..., 0.18657006, 0.892559  ,
        0.53934224],
       ...,
       [0.81783422, 0.12020906, 0.5444891 , ..., 0.89803055, 0.2434823 ,
        0.92703454],
       [0.06026739, 0.93443603, 0.35162269, ..., 0.41102847, 0.8398613 ,
        0.90002312],
       [0.35342138, 0.23687056, 0.78052552, ..., 0.07941937, 0.08565825,
        0.89419087]])

`np.set_printoptions()` 의 기능을 다음 두 개의 예를 이용하여 설명하라.

In [5]:
np.set_printoptions(precision=4)

In [6]:
Z

array([[0.3745, 0.9507, 0.732 , ..., 0.0977, 0.6842, 0.4402],
       [0.122 , 0.4952, 0.0344, ..., 0.074 , 0.3585, 0.1159],
       [0.8631, 0.6233, 0.3309, ..., 0.1866, 0.8926, 0.5393],
       ...,
       [0.8178, 0.1202, 0.5445, ..., 0.898 , 0.2435, 0.927 ],
       [0.0603, 0.9344, 0.3516, ..., 0.411 , 0.8399, 0.9   ],
       [0.3534, 0.2369, 0.7805, ..., 0.0794, 0.0857, 0.8942]])

In [7]:
np.set_printoptions(precision=6)

In [8]:
Z

array([[0.37454 , 0.950714, 0.731994, ..., 0.097672, 0.684233, 0.440152],
       [0.122038, 0.495177, 0.034389, ..., 0.074045, 0.358466, 0.115869],
       [0.863103, 0.623298, 0.330898, ..., 0.18657 , 0.892559, 0.539342],
       ...,
       [0.817834, 0.120209, 0.544489, ..., 0.898031, 0.243482, 0.927035],
       [0.060267, 0.934436, 0.351623, ..., 0.411028, 0.839861, 0.900023],
       [0.353421, 0.236871, 0.780526, ..., 0.079419, 0.085658, 0.894191]])

`코드설명`: 반올림해서 소수점 지정한 자리까지 나타낸다. 맨 뒤에 0이 오면 0이 아닌 숫자가 올 때까지 0을 버린다.

아래 코드는 기본 옵션값으로 되돌린다. 수정하지 마세요.

In [9]:
np.set_printoptions(precision=8)

## 1차원 어레이

**문제 1**

크기가 10이고 모든 항목이 0인 1차원 어레이를
변수 `Z`가 가리키도록 하라.
단, `np.zeros()` 함수를 반드시 이용한다.

In [10]:
# None을 적절한 표현식으로 대체하라.
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

아래 코드는 수정하지 마세요!!!

In [11]:
assert (Z == np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])).all()

**문제 2**

변수 `Z`가 10에서 49까지의 정수 중에서 짝수로만 구성된 1차원 어레이를 가리키도록 하라.
단, `np.arange()` 함수를 반드시 이용한다.

In [12]:
# None을 적절한 표현식으로 대체하라.
Z = np.arange(10, 49, 2)
Z

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

아래 코드는 수정하지 마세요!!!

In [13]:
assert (Z == np.array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
                        44, 46, 48])).all()

**문제 3**

변수 `Z`가 아래와 같이 선언되었다.

In [14]:
Z = np.array([2, 3, 1, 0, 4])
Z

array([2, 3, 1, 0, 4])

변수 `Z`의 항목을 정렬하라.
단, sort() 메서드를 활용한다.

In [15]:
# None을 적절한 표현식으로 대체하라.
Z.sort()
Z

array([0, 1, 2, 3, 4])

아래 코드는 수정하지 마세요!!!

In [16]:
assert (Z == np.arange(5)).all()

**문제 4**

변수 `Z`가 크기 30이며 무작위로 생성된 1차원 어레이를 가리키도록 하라.
또한 포함된 항목들의 평균값을 계산하라.
단, 어레이의 항목은 0과 1 사이의 임의의 부동소수점으로 구성되어야 한다.
`np.random.random()` 함수, `mean()` 어레이 메서드를 반드시 이용한다.

In [17]:
# None을 적절한 표현식으로 대체하라.
Z = np.random.random(30)
Z_mean = Z.mean()

아래 코드는 수정하지 마세요!!!

In [18]:
assert (Z.shape == (30,))
print(f"1차원 어레이 평균값: {Z_mean}")

1차원 어레이 평균값: 0.4618868095723934


**문제 5**

1차원 어레이가 다음과 같이 주어졌다.

In [19]:
Z = np.arange(1, 4)

(1) 아래 표현식의 계산 결과를 설명하라.

In [20]:
Z*Z

array([1, 4, 9])

`코드설명`: 1부터 3까지의 정수 어레이를 같은 항목끼리 곱한 결괏값

(2) 아래 표현식의 계산 결과를 설명하라.

In [21]:
Z**Z

array([ 1,  4, 27])

`코드설명`: 1부터 3까지의 정수 어레이를 같은 항목끼지 거듭제곱한 결괏값

(3) 아래 표현식의 계산 결과를 설명하라.

In [22]:
Z < -Z

array([False, False, False])

`코드설명`: 1부터 3까지의 정수 어레이가 -3부터 -1까지의 음의 정수 어레이보다 작은지 비교 연산한 결괏값

(4) 아래 표현식의 계산 결과를 설명하라.

In [23]:
Z/1/1

array([1., 2., 3.])

`코드설명`: 1부터 3까지의 정수 어레이의 각 항목을 1로 두번 나눈 결괏값

**문제 6**

변수 `Z`가 아래 모양의 어레이를 가리키도록 하라.
단, `np.linspace()` 함수와 `endpoint` 키워드 인자를 이용한다.

```
[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
```

In [24]:
# None을 적절한 표현식으로 대체하라.
Z = np.linspace(0, 1, 10, endpoint = False)

아래 코드는 수정하지 마세요!!!

In [25]:
assert np.isclose(Z, np.array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])).all()

**문제 7**

아래 코드의 실행결과를 설명하라.

In [26]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


`코드설명`: Z.itemsize는 배열의 각 요소의 바이트 사이즈로 float64 이므로 8byte이다. Z.size는 전체 요소의 개수로 100개 이므로 Z.size * Z.itemsize는 800이다.

**문제 8**

아래 코드의 실행결과를 설명하라.

In [27]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


`코드설명`: Z.itemsize는 배열의 각 요소의 바이트 사이즈로 float64 이므로 8byte이다. Z.size는 전체 요소의 개수로 100개 이므로 Z.size * Z.itemsize는 800이다.

**문제 9**

다음 리스트에서 0이 아닌 항목들의 인덱스로 구성된 어레이를 한줄 코드로 생성하라. 
단. `np.nonzero()` 함수를 활용한다.

In [28]:
Z = [1, 2, 0, 0, 4, 0]

In [29]:
# None을 적절한 표현식으로 대체하라.

non_zeros = np.nonzero(Z)
non_zeros

(array([0, 1, 4]),)

아래 코드는 수정하지 마세요!!!

In [30]:
assert (non_zeros == np.array([0, 1, 4])).all()

**문제 10**

두 개의 1차원 어레이가 다음과 같이 주어졌다.

In [31]:
A = np.ones(3)*1
B = np.ones(3)*2

아래 코드의 실행 결과를 설명하라.

In [32]:
(A+B)*(-A/2)

array([-1.5, -1.5, -1.5])

`코드설명`: A는 1로 이루어진 사이즈가 3인 어레이고 B는 2로 이루어진 사이즈가 3인 어레이다. (A+B)는 A와 B를 같은 항목끼리 더한 값으로 3으로 이루어진 사이즈가 3인 어레이다. (-A/2)는 A의 각 항목을 -1/2로 곱한 값으로 -1/2로 이루어진 사이즈가 3인 어레이다. 따라서 (A+B)*(-A/2)를 하면 위와 같은 결과가 나온다.

In [33]:
np.add(A,B,out=B)

array([3., 3., 3.])

`코드설명`: A와 B를 같은 항목끼리 더하고 그 값을 B에 저장한다.

In [34]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

`코드설명`: A의 각 항목을 2로 나누고 그 값을 A에 저장한다.

In [35]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

`코드설명`: A의 각 항목에 -1을 곱하고 그 값을 A에 저장한다.

In [36]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

`코드설명`: A와 B를 같은 항목끼리 곱하고 그 값을 A에 저장한다.

## 2차원 어레이

**문제 1**

변수 `Z`가 (5, 5) 모양의 2차원 어레이를 가리키도록 하라.
단, 어레이의 항목은 0과 1 사이의 임의의 부동소수점으로 구성되어야 한다.
또한 `np.random.random()` 함수를 이용한다.

In [37]:
# None을 적절한 표현식으로 대체하라.
Z = np.random.random([5,5])
Z

array([[0.75616333, 0.34757152, 0.66491172, 0.79544996, 0.92717782],
       [0.23464208, 0.39931592, 0.15241601, 0.9924835 , 0.92700097],
       [0.53995713, 0.84203329, 0.52095798, 0.62358569, 0.08912443],
       [0.75527042, 0.12771348, 0.82606763, 0.78202809, 0.7087447 ],
       [0.03616038, 0.30312836, 0.26311257, 0.36013641, 0.08764275]])

아래 코드는 수정하지 마세요!!!

In [38]:
assert (Z.shape == (5, 5))
assert (Z.dtype == np.float64)

**문제 2**

변수 `Z`가 0에서 8까지의 정수로 이루어진 (3, 3) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.arange()` 함수와 `reshape()` 어레이 메서드를 반드시 이용한다.

In [39]:
# None을 적절한 표현식으로 대체하라.
Z = np.arange(0, 9).reshape(3, 3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

아래 코드는 수정하지 마세요!!!

In [40]:
assert (Z == np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])).all()

**문제 3**

변수 `Z`가 (3, 3) 모양의 2차원 어레이를 가리키도록 하라.
단, 2차원 어레이의 대각선 상은 1이고 나머지는 0이어야 한다.
또한 `np.eye()` 함수를 반드시 이용한다.

In [41]:
# None을 적절한 표현식으로 대체하라.
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

아래 코드는 수정하지 마세요!!!

In [42]:
assert (Z == np.array([[1., 0., 0.],
                       [0., 1., 0.],
                       [0., 0., 1.]])).all

**문제 4**

변수 `Z`가 아래와 같은 (5,5) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.arange()` 함수와 `np.diag()` 함수의 `k` 키워드 인자를 반드시 활용한다.

```
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
```

In [43]:
# None을 적절한 표현식으로 대체하라.
Z = np.arange(1, 5)
Z = np.diag(Z, k = -1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

아래 코드는 수정하지 마세요!!!

In [44]:
assert (Z == np.array([[0, 0, 0, 0, 0],
                        [1, 0, 0, 0, 0],
                        [0, 2, 0, 0, 0],
                        [0, 0, 3, 0, 0],
                        [0, 0, 0, 4, 0]])).all()

**문제 5**

변수 `Z`가 아래와 같은 (5, 5) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.zeros()` 함수, `np.arange()` 함수, 2차원 어레이 덧셈을 이용한다.

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [45]:
# None을 적절한 표현식으로 대체하라.
Z = np.zeros((5, 5)) + np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

아래 코드는 수정하지 마세요!!!

In [46]:
assert (Z == np.array([[0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.]])).all()

**문제 6**

아래 3x3 단위 행렬에 해당하는 2차원 어레이를 한줄 코드로 생성하라.
단, `np.eye()` 함수를 이용한다.

```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [47]:
# None을 적절한 표현식으로 대체하라.
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

아래 코드는 수정하지 마세요!!!

In [48]:
assert (Z == np.array([[1., 0., 0.],
                       [0., 1., 0.],
                       [0., 0., 1.]])).all()

**문제 7**

무작위 수로 구성된 (5, 5) 모양의 2차원 어레이가 다음과 같다.

In [49]:
Z = np.random.random((5, 5))
Z

array([[0.93695782, 0.55380224, 0.30552431, 0.39698152, 0.44720254],
       [0.60059433, 0.51567943, 0.91939197, 0.49696348, 0.99215801],
       [0.85142496, 0.20851051, 0.93059521, 0.1163664 , 0.81744971],
       [0.38062329, 0.87797432, 0.86805669, 0.8059254 , 0.79003044],
       [0.30467914, 0.08091928, 0.40298018, 0.17352451, 0.69495109]])

변수 `Z`가 가리키는 2차원 어레이에 대해 min-max 크기조정(정규화)을 적용하라.

min-max 크기조정(정규화)은 항목의 모든 값을 아래 식을 통해 0과 1 사이의 부동소수점으로 변환한다. $max$와 $min$은 각각 최대 항목과 최소 항목을 가리킨다.

$$
\frac{x-min}{max - min}
$$

In [50]:
# None을 적절한 표현식으로 대체하라.
Z = (Z - Z.min()) / (Z.max() - Z.min())
Z

array([[0.93942291, 0.51894519, 0.24648319, 0.34684899, 0.40196191],
       [0.57029517, 0.47710894, 0.92014602, 0.45656993, 1.        ],
       [0.84555852, 0.14001954, 0.93244054, 0.03889992, 0.80827384],
       [0.32889736, 0.87469398, 0.86381031, 0.79562698, 0.77818373],
       [0.24555569, 0.        , 0.35343197, 0.10162565, 0.67384296]])

아래 코드는 수정하지 마세요!!!

In [51]:
assert (Z.max() == 1 and Z.min() == 0)

## 3차원 어레이

**문제 1**

(1) 변수 `Z`가 (3, 3, 3) 모양의 3차원 어레이를 가리키도록 하라.
단, 어레이의 항목은 0과 1 사이의 임의의 부동소수점으로 구성되어야 한다.
또한 `np.random.random()` 함수를 이용한다.

In [52]:
# None을 적절한 표현식으로 대체하라.
Z = np.random.random((3, 3, 3))
Z

array([[[0.34609973, 0.9756102 , 0.64097208],
        [0.82248056, 0.13252467, 0.86201448],
        [0.92275719, 0.48706192, 0.60625294]],

       [[0.7648098 , 0.17483863, 0.50256608],
        [0.39866303, 0.14637399, 0.36753442],
        [0.06817231, 0.02581191, 0.13516629]],

       [[0.96311511, 0.54952954, 0.96582216],
        [0.43249788, 0.31181613, 0.50614186],
        [0.43951169, 0.10566468, 0.64082631]]])

아래 코드는 수정하지 마세요!!!

In [53]:
assert (Z.shape == (3, 3, 3))
assert (Z.dtype == 'f8')

(2) `Z`에 포함된 항목들 중에서 최댓값과 최솟값의 차이를 구하라.
단, `maximum`, `mininum` 두 변수가 각각 최댓값과 최솟값을 가리키도록 하며,
`max()`와 `min()` 어레이 메서드를 이용한다.

In [54]:
# None을 적절한 표현식으로 대체하라.
maximum = Z.max()
minimum = Z.min()

아래 코드는 수정하지 마세요!!!

In [55]:
print(f"최댓값과 최솟값의 차이: {maximum - minimum}")

최댓값과 최솟값의 차이: 0.9497982939104279


## `dtype` 종류 

**문제 1**

아래 두 코드의 실행결과를 설명하라.

In [56]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


`코드설명`: np.iinfo().min은 받은 정수형의 범위중 최소값을 나타낸다. np.iinfo().max는 받은 정수형의 범위중 최소값을 나타낸다. 첫 두 줄은 int8이 표현 가능한 범위, 다음 두 줄은 int32가 표현 가능한 범위, 마지막 두 줄은 int64가 표현 가능한 범위를 의미한다.


In [57]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).esp)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


`코드설명`: np.finfo().min은 받은 실수형의 범위중 최소값을 나타낸다. np.finfo().max는 받은 실수형의 범위중 최대값을 나타낸다. np.finfo().esp는 1과 1바로 위 실수와의 간격을 의미한다. float32는 2\*\*(-23), float64는 2**(-52)를 의미한다.

**문제 2**

부동소수점으로 구성된 1차원 어레이가 아래와 같이 주어졌다.

In [70]:
Z = (np.random.rand(10)*100).astype(np.float32)
Z

array([ 7.2084336,  7.125673 ,  1.2108475, 95.65014  , 73.75084  ,
       35.32514  , 29.653559 , 34.97032  , 77.465355 , 66.13706  ],
      dtype=float32)

변수 `Y`가 변수 `Z`가 가리키는 1차원 어레이의 dtype이 `int32`로 형변환된 1차원 어레이를 가리키도록 하라.
단, `astype()` 메서드를 이용한다.

In [72]:
# None을 적절한 표현식으로 대체하라.
Y = Z.astype(dtype = 'int32')
Y

array([ 7,  7,  1, 95, 73, 35, 29, 34, 77, 66], dtype=int32)

아래 코드는 수정하지 마세요!!!

In [73]:
assert (Y.shape == (10,))
assert (Y.dtype == np.int32)

**문제 3**

변수 `Z`가 아래와 같이 무작위로 생성된 길이가 10인 1차원 어레이를 가리킨다.

In [118]:
Z = np.random.uniform(0,10,10)
Z

array([5.08360547, 2.97548451, 5.65021993, 6.88885302, 8.73322916,
       6.36291354, 7.61121537, 1.60071635, 4.61557474, 0.0933162 ])

(1) 나머지 연산자(`%`)를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라. 

In [101]:
# None을 적절한 표현식으로 대체하라.
Y = Z-(Z%1)
Y

array([9., 7., 2., 9., 6., 5., 7., 8., 6., 1.])

아래 코드는 수정하지 마세요!!!

In [102]:
assert (Y == Z.astype(np.int32)).all()

(2) 몫 연산자(`//`)를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라.

In [111]:
# None을 적절한 표현식으로 대체하라.
Y = Z // 1
Y

array([4., 8., 7., 7., 6., 1., 5., 9., 9., 0.])

아래 코드는 수정하지 마세요!!!

In [112]:
assert (Y == Z.astype(np.int32)).all()

(3) 내림 함수 `np.floor()` 함수를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라. 

In [115]:
# None을 적절한 표현식으로 대체하라.
Y = np.floor(Z)
Y

array([1., 1., 7., 8., 2., 5., 8., 7., 5., 5.])

아래 코드는 수정하지 마세요!!!

In [116]:
assert (Y == Z.astype(np.int32)).all()

(4) `np.trunc()` 함수를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라. 

In [119]:
# None을 적절한 표현식으로 대체하라.
Y = np.trunc(Z)
Y

array([5., 2., 5., 6., 8., 6., 7., 1., 4., 0.])

아래 코드는 수정하지 마세요!!!

In [120]:
assert (Y == Z.astype(np.int32)).all()